/* Rebuilds availability.json from a Google Calendar ICS feed.
   Run by .github/workflows/sync-availability.yml, not by hand.

   Reads the feed, collects every date that has at least one busy event on
   it, merges in any manual holds, writes the file. Only dates are ever
   written out — no titles, no times, no client names, nothing that
   identifies who is in the chair. */

import { writeFileSync, readFileSync } from 'node:fs';
import ical from 'node-ical';

const ICS_URL = process.env.CALENDAR_ICS_URL;
const OUT = 'availability.json';
const MONTHS_AHEAD = 4;

if (!ICS_URL) {
  console.error('CALENDAR_ICS_URL is not set. Add it as a repository secret.');
  process.exit(1);
}

/* Local-time date key. Never use toISOString() here — that converts to UTC,
   and a 6pm Texas appointment becomes midnight the next day, marking the
   wrong square. */
function key(d) {
  return d.getFullYear() + '-' +
    String(d.getMonth() + 1).padStart(2, '0') + '-' +
    String(d.getDate()).padStart(2, '0');
}

function datesBetween(start, end) {
  const out = [];
  const cur = new Date(start.getFullYear(), start.getMonth(), start.getDate());
  const last = new Date(end.getFullYear(), end.getMonth(), end.getDate());
  /* Google stores an all-day event's DTEND as the day AFTER it finishes,
     so a single all-day event ends up spanning two dates unless we back
     the end off by one. Timed events don't have this quirk. */
  while (cur <= last) {
    out.push(key(cur));
    cur.setDate(cur.getDate() + 1);
  }
  return out;
}

const today = new Date();
const horizon = new Date(today.getFullYear(), today.getMonth() + MONTHS_AHEAD, 0);
const todayKey = key(today);

const events = await ical.async.fromURL(ICS_URL);
const booked = new Set();

function markSpan(start, end, isAllDay) {
  let stop = new Date(end);
  /* Google stores an all-day event's DTEND as the day AFTER it finishes,
     so a one-day event would otherwise span two squares. */
  if (isAllDay && stop > start) stop = new Date(stop.getTime() - 1);
  if (stop < today || start > horizon) return;
  for (const k of datesBetween(start, stop)) {
    if (k >= todayKey) booked.add(k);
  }
}

for (const ev of Object.values(events)) {
  if (ev.type !== 'VEVENT') continue;
  if (ev.transparency === 'TRANSPARENT') continue;   // marked "free" in Google
  if (ev.status === 'CANCELLED') continue;
  if (!ev.start) continue;

  const start = new Date(ev.start);
  const end = ev.end ? new Date(ev.end) : new Date(ev.start);
  const isAllDay = ev.datetype === 'date';

  if (!ev.rrule) {
    markSpan(start, end, isAllDay);
    continue;
  }

  /* Repeating event: expand it. Without this, a standing weekly slot only
     ever marks its first occurrence and every later week looks open. */
  const duration = end.getTime() - start.getTime();
  const skip = new Set(Object.keys(ev.exdate || {}));
  const moved = new Set(
    Object.values(ev.recurrences || {}).map(r => key(new Date(r.start)))
  );

  for (const occ of ev.rrule.between(today, horizon, true)) {
    const k = key(occ);
    if (skip.has(k) || moved.has(k)) continue;
    markSpan(occ, new Date(occ.getTime() + duration), isAllDay);
  }

  /* Instances she dragged to a different day come through separately. */
  for (const r of Object.values(ev.recurrences || {})) {
    if (r.status === 'CANCELLED') continue;
    const rs = new Date(r.start);
    markSpan(rs, r.end ? new Date(r.end) : rs, isAllDay);
  }
}

/* Manual holds survive the rebuild. Anything she blocks off by hand —
   a convention, time off, a day she just doesn't want to work — lives in
   the holds array and gets merged back in every run. */
let holds = [];
try {
  const existing = JSON.parse(readFileSync(OUT, 'utf8'));
  if (Array.isArray(existing.holds)) holds = existing.holds;
} catch {
  console.log('No readable ' + OUT + ' yet — writing a fresh one.');
}

for (const h of holds) if (h >= todayKey) booked.add(h);

const payload = {
  _comment: 'Generated by scripts/sync-availability.mjs. Do not hand-edit "booked" — it is overwritten every run. Add manual blocks to "holds" instead.',
  updated: todayKey,
  holds,
  booked: [...booked].sort()
};

writeFileSync(OUT, JSON.stringify(payload, null, 2) + '\n');
console.log('Wrote ' + payload.booked.length + ' booked dates (' + holds.length + ' manual holds).');
